services:
  - type: web
    name: app
    env: python
    plan: free
    buildCommand: pip install conda && conda create --name my-env --file conda_requirements.txt
    startCommand: conda activate my-env && uvicorn main:app --reload --workers 1 --host localhost --port 8008